# ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory ~/config/ansible/config_vm.yml
---
- hosts: simulators
  roles:
  tasks:
    - name: Copy ssh config into VM (for github)
      copy:
        src=~/.ssh/{{ item }}
        dest=~/.ssh/{{ item }}
        mode=0600
      with_items:
        - id_rsa
        - id_rsa.pub
      become: yes
      become_user: iron

    - name: Download config repo
      git:
        repo=git@github.com:jonbinney/jdb-config
        dest=~/config
        accept_hostkey=yes
        update=yes
      become: yes
      become_user: iron

    - name: Run config script
      command: python ~/config/setup.py
      become: yes
      become_user: iron

    - name: Install handy APT packages
      apt:
        name={{ item }}
        state=present
      with_items:
        - build-essential
        - ipython
        - python-scipy
        - python-matplotlib
        - scons
        - vim-nox
        - mercurial
        - git
        - subversion
        - openssh-server
        - cmake
        - python-setuptools
        - tmux
        - ruby-dev
        - xclip
        - cmake
        - python-dev
      become: yes

    - name: Download Command-T
      git:
        repo=https://github.com/wincent/command-t.git
        dest=~/config/vim/bundle/command-t
      become: yes
      become_user: iron

    - name: Build Command-T
      command: ruby extconf.rb
        chdir=~/config/vim/bundle/command-t/ruby/command-t
      become: yes
      become_user: iron

    # Doesn't need to be built; just downloaded
    - name: Download NerdTree
      git:
        repo=https://github.com/scrooloose/nerdtree.git
        dest=~/config/vim/bundle/nerdtree
      become: yes
      become_user: iron

    - name: Download YCM
      git:
        repo=https://github.com/Valloric/YouCompleteMe.git
        dest=~/config/vim/bundle/YouCompleteMe
        recursive=yes
        force=yes
      become: yes
      become_user: iron

    - name: Build YCM
      command: python install.py --clang-completer
        chdir=~/config/vim/bundle/YouCompleteMe
      become: yes
      become_user: iron

